import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, Pressable, ActivityIndicator, StyleSheet } from 'react-native';
import { Image } from 'expo-image';
import { useNavigation, useRoute } from '@react-navigation/native';
import { getCharacter, CharacterDetail } from '../api/content';
import { colors, radius, fonts } from '../theme';
import { WebHeader, WebSectionHeader, WebFooter } from '../components/WebChrome';

export default function CharacterScreen() {
  const navigation=useNavigation<any>(); const route=useRoute<any>(); const {id}=route.params as {id:number};
  const [character,setCharacter]=useState<CharacterDetail|null>(null); const [animeography,setAnimeography]=useState<any[]>([]); const [voices,setVoices]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const load=()=>{setLoading(true);setError(null);getCharacter(id).then(res=>{setCharacter(res.character);setAnimeography(res.animeography);setVoices(res.voices)}).catch(e=>setError(e?.message??'Unable to load character.')).finally(()=>setLoading(false))}; useEffect(load,[id]);
  if(loading&&!character)return <View style={styles.center}><ActivityIndicator color={colors.accent}/></View>;
  return <ScrollView style={styles.container} showsVerticalScrollIndicator={false}><WebHeader title="Character" onSearch={()=>{}} onMenu={()=>navigation.navigate('Menu')}/>{error&&!character?<View style={styles.error}><Text style={styles.errorTitle}>CHARACTER UNAVAILABLE</Text><Text style={styles.errorText}>{error}</Text><Pressable style={styles.retry} onPress={load}><Text style={styles.retryText}>RETRY</Text></Pressable></View>:character?<><View style={styles.hero}><View style={styles.heroInner}><Image source={{uri:character.image}} style={styles.avatar} contentFit="cover"/><View style={styles.heroCopy}><Text style={styles.kicker}>CHARACTER PROFILE</Text><Text style={styles.name}>{character.name}</Text>{character.nameKanji&&<Text style={styles.kanji}>{character.nameKanji}</Text>}{character.nicknames.length>0&&<Text style={styles.nicknames}>{character.nicknames.join(' · ')}</Text>}<Text style={styles.favorites}>♥ {character.favorites.toLocaleString()} FAVORITES</Text></View></View></View>{character.about&&<View style={styles.section}><WebSectionHeader title="ABOUT"/><Text style={styles.about}>{character.about}</Text></View>}{animeography.length>0&&<View style={styles.section}><WebSectionHeader title="APPEARS IN"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{animeography.map((a,i)=><Pressable key={`${a.animeId}-${i}`} style={styles.animeCard} onPress={()=>a.animeId&&navigation.navigate('AnimeDetail',{id:a.animeId,title:a.title})}><Image source={{uri:a.image}} style={styles.poster} contentFit="cover"/><Text style={styles.cardTitle} numberOfLines={2}>{a.title}</Text><Text style={styles.role}>{a.role}</Text></Pressable>)}</ScrollView></View>}{voices.length>0&&<View style={styles.section}><WebSectionHeader title="VOICE ACTORS"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.row}>{voices.map((v,i)=><View key={`${v.name}-${i}`} style={styles.voiceCard}><Image source={{uri:v.image}} style={styles.voice} contentFit="cover"/><Text style={styles.cardTitle} numberOfLines={2}>{v.name}</Text><Text style={styles.role}>{v.language}</Text></View>)}</ScrollView></View>}<WebFooter/></>:null}</ScrollView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.bgBase},center:{flex:1,backgroundColor:colors.bgBase,alignItems:'center',justifyContent:'center'},hero:{padding:16,paddingTop:20},heroInner:{backgroundColor:colors.bgSurface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:16,flexDirection:'row',alignItems:'center'},avatar:{width:105,height:140,borderRadius:radius.md,backgroundColor:colors.bgCard},heroCopy:{flex:1,paddingLeft:15},kicker:{color:colors.accent,fontFamily:fonts.displayMedium,fontSize:8,letterSpacing:1.4},name:{color:colors.textPrimary,fontFamily:fonts.display,fontSize:20,marginTop:6},kanji:{color:colors.textMuted,fontFamily:fonts.body,fontSize:12,marginTop:2},nicknames:{color:colors.textSecondary,fontFamily:fonts.body,fontSize:11,marginTop:5,lineHeight:17},favorites:{color:colors.accent,fontFamily:fonts.bodyBold,fontSize:9,marginTop:9,letterSpacing:.5},section:{paddingHorizontal:16,marginTop:5,marginBottom:10},about:{color:colors.textSecondary,fontFamily:fonts.body,fontSize:12,lineHeight:19},row:{gap:10,paddingBottom:5},animeCard:{width:105},poster:{width:105,height:148,borderRadius:radius.sm,backgroundColor:colors.bgCard},cardTitle:{color:colors.textPrimary,fontFamily:fonts.bodyMedium,fontSize:10,lineHeight:14,marginTop:5},role:{color:colors.textMuted,fontFamily:fonts.body,fontSize:9,marginTop:2},voiceCard:{width:85,alignItems:'center'},voice:{width:68,height:68,borderRadius:34,backgroundColor:colors.bgCard},error:{padding:50,alignItems:'center'},errorTitle:{color:colors.accent,fontFamily:fonts.displayMedium,fontSize:10,letterSpacing:1},errorText:{color:colors.textMuted,fontFamily:fonts.body,fontSize:11,textAlign:'center',marginTop:7},retry:{marginTop:14,backgroundColor:colors.accent,paddingHorizontal:18,paddingVertical:9,borderRadius:radius.sm},retryText:{color:'#fff',fontFamily:fonts.bodyBold,fontSize:10}});