import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { View, Text, FlatList, Pressable, ActivityIndicator, StyleSheet, RefreshControl } from 'react-native';
import { Image } from 'expo-image';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { getSchedule, ScheduleCard } from '../api/content';
import { colors, radius, fonts } from '../theme';

const days=[['monday','Mon'],['tuesday','Tue'],['wednesday','Wed'],['thursday','Thu'],['friday','Fri'],['saturday','Sat'],['sunday','Sun']] as const;
export default function ScheduleScreen(){
 const navigation=useNavigation<any>(); const today=useMemo(()=>{const d=new Date().getUTCDay();return ['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][d]},[]); const [day,setDay]=useState(today); const [items,setItems]=useState<ScheduleCard[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async(d:string)=>{setLoading(true);setError(null);try{const r=await getSchedule(d);setItems(r.data)}catch(e:any){setError(e.message??'Failed to load schedule.')}finally{setLoading(false)}},[]); useEffect(()=>{load(day)},[day,load]); const refresh=async()=>{setRefreshing(true);await load(day);setRefreshing(false)};
 return <View style={styles.container}><View style={styles.head}><View><Text style={styles.title}>Schedule</Text><Text style={styles.subtitle}>Weekly airing schedule</Text></View><Ionicons name="calendar-outline" size={27} color={colors.accent}/></View><FlatList horizontal data={days} keyExtractor={x=>x[0]} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.days} renderItem={({item})=><Pressable onPress={()=>setDay(item[0])} style={[styles.day,day===item[0]&&styles.dayActive]}><Text style={[styles.dayText,day===item[0]&&styles.dayTextActive]}>{item[1]}</Text>{today===item[0]&&<View style={styles.dot}/>}</Pressable>}/>{error&&<View style={styles.error}><Ionicons name="cloud-offline-outline" size={18} color={colors.accent}/><Text style={styles.errorText}>{error}</Text></View>}<FlatList data={items} keyExtractor={x=>String(x.id)} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.accent}/>} ListEmptyComponent={!loading?<View style={styles.empty}><Ionicons name="calendar-outline" size={42} color={colors.textMuted}/><Text style={styles.emptyTitle}>No shows scheduled</Text><Text style={styles.emptyText}>There may be no entries for this day.</Text></View>:null} ListFooterComponent={loading?<ActivityIndicator color={colors.accent} style={{margin:20}}/>:null} renderItem={({item})=><Pressable style={styles.row} onPress={()=>navigation.navigate('AnimeDetail',{id:item.id,title:item.title})}><Image source={{uri:item.image}} style={styles.poster} contentFit="cover"/><View style={styles.info}><Text style={styles.time}>{item.broadcast?.time||'TBA'}</Text><Text style={styles.name} numberOfLines={2}>{item.title}</Text><Text style={styles.meta}>{item.type||'Anime'}{item.episodes?` • ${item.episodes} eps`:''}</Text></View>{item.score!=null&&<View style={styles.score}><Ionicons name="star" size={11} color={colors.gold}/><Text style={styles.scoreText}>{item.score.toFixed(1)}</Text></View>}<Ionicons name="chevron-forward" size={18} color={colors.textMuted}/></Pressable>}/></View>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.bgBase},head:{padding:14,paddingTop:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:colors.textPrimary,fontSize:20,fontFamily:fonts.displayMedium},subtitle:{color:colors.textMuted,fontSize:11,fontFamily:fonts.body,marginTop:4},days:{paddingHorizontal:12,paddingBottom:10,gap:8},day:{minWidth:55,alignItems:'center',paddingVertical:8,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.bgCard,marginRight:7,position:'relative'},dayActive:{backgroundColor:colors.accent,borderColor:colors.accent},dayText:{color:colors.textSecondary,fontSize:11,fontFamily:fonts.bodyMedium},dayTextActive:{color:'#fff'},dot:{width:5,height:5,borderRadius:3,backgroundColor:colors.gold,marginTop:3},list:{padding:12,paddingTop:4,paddingBottom:28,gap:7},row:{minHeight:92,flexDirection:'row',alignItems:'center',gap:11,padding:9,backgroundColor:colors.bgCard,borderRadius:radius.md,borderWidth:1,borderColor:colors.border},poster:{width:50,height:70,borderRadius:radius.sm,backgroundColor:colors.bgSurface},info:{flex:1,minWidth:0},time:{color:colors.accent,fontSize:12,fontFamily:fonts.bodyBold,marginBottom:3},name:{color:colors.textPrimary,fontSize:13,fontFamily:fonts.bodySemibold,lineHeight:17},meta:{color:colors.textMuted,fontSize:10,fontFamily:fonts.body,marginTop:4},score:{flexDirection:'row',alignItems:'center',gap:3,backgroundColor:colors.bgSurface,paddingHorizontal:6,paddingVertical:4,borderRadius:5},scoreText:{color:colors.textPrimary,fontSize:9,fontFamily:fonts.bodySemibold},error:{margin:12,padding:10,flexDirection:'row',gap:8,alignItems:'center',backgroundColor:colors.bgCard,borderWidth:1,borderColor:colors.border,borderRadius:radius.md},errorText:{flex:1,color:colors.textSecondary,fontSize:12,fontFamily:fonts.body},empty:{alignItems:'center',paddingTop:65,paddingHorizontal:30},emptyTitle:{color:colors.textPrimary,fontSize:16,fontFamily:fonts.displayMedium,marginTop:12},emptyText:{color:colors.textMuted,fontSize:12,fontFamily:fonts.body,marginTop:5,textAlign:'center'}});
