import React, { useCallback, useEffect, useState } from 'react';
import { View, Text, FlatList, Pressable, ActivityIndicator, StyleSheet, RefreshControl } from 'react-native';
import { Image } from 'expo-image';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { getTopAnime, DiscoveryCard } from '../api/content';
import { colors, radius, fonts } from '../theme';

const filters = [['bypopularity','Most Popular'],['favorite','Most Favorited'],['airing','Top Airing'],['upcoming','Upcoming'],['byrank','By Score']] as const;
export default function TopAnimeScreen() {
  const navigation=useNavigation<any>(); const [filter,setFilter]=useState('bypopularity'); const [items,setItems]=useState<DiscoveryCard[]>([]); const [page,setPage]=useState(1); const [hasNext,setHasNext]=useState(false); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async(f:string,p=1,append=false)=>{setLoading(true);setError(null);try{const r=await getTopAnime(f,p);setItems(v=>append?[...v,...r.data]:r.data);setPage(p);setHasNext(!!r.pagination?.has_next_page)}catch(e:any){setError(e.message??'Failed to load top anime.')}finally{setLoading(false)}},[]);
  useEffect(()=>{load(filter)},[filter,load]); const more=()=>{if(!loading&&hasNext)load(filter,page+1,true)}; const refresh=async()=>{setRefreshing(true);await load(filter);setRefreshing(false)};
  return <View style={styles.container}><View style={styles.head}><View><Text style={styles.title}>Top Anime</Text><Text style={styles.subtitle}>Discover what everyone is watching</Text></View><Ionicons name="trophy-outline" size={27} color={colors.gold}/></View><FlatList horizontal data={filters} keyExtractor={x=>x[0]} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters} renderItem={({item})=><Pressable onPress={()=>setFilter(item[0])} style={[styles.chip,filter===item[0]&&styles.chipActive]}><Text style={[styles.chipText,filter===item[0]&&styles.chipTextActive]}>{item[1]}</Text></Pressable>}/>{error&&<View style={styles.error}><Ionicons name="cloud-offline-outline" size={18} color={colors.accent}/><Text style={styles.errorText}>{error}</Text></View>}<FlatList data={items} numColumns={3} keyExtractor={x=>String(x.id)} contentContainerStyle={styles.grid} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.accent}/>} onEndReached={more} onEndReachedThreshold={.55} ListEmptyComponent={!loading?<View style={styles.empty}><Ionicons name="trophy-outline" size={42} color={colors.textMuted}/><Text style={styles.emptyTitle}>No rankings available</Text><Text style={styles.emptyText}>Try refreshing in a moment.</Text></View>:null} ListFooterComponent={loading?<ActivityIndicator color={colors.accent} style={{margin:20}}/>:null} renderItem={({item,index})=><Pressable style={styles.card} onPress={()=>navigation.navigate('AnimeDetail',{id:item.id,title:item.title})}><View><Image source={{uri:item.image}} style={styles.poster} contentFit="cover" transition={150}/><View style={styles.rank}><Text style={styles.rankText}>#{item.rank ?? index+1}</Text></View>{item.score!=null&&<View style={styles.score}><Ionicons name="star" size={9} color={colors.gold}/><Text style={styles.scoreText}>{item.score.toFixed(1)}</Text></View>}</View><Text style={styles.cardTitle} numberOfLines={2}>{item.title}</Text><Text style={styles.meta} numberOfLines={1}>{item.type||'Anime'}{item.episodes?` • ${item.episodes} eps`:''}</Text></Pressable>}/></View>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.bgBase},head:{padding:14,paddingTop:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:colors.textPrimary,fontSize:20,fontFamily:fonts.displayMedium},subtitle:{color:colors.textMuted,fontSize:11,fontFamily:fonts.body,marginTop:4},filters:{paddingHorizontal:12,paddingBottom:10,gap:8},chip:{paddingHorizontal:13,paddingVertical:8,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.bgCard,marginRight:7},chipActive:{backgroundColor:colors.accent,borderColor:colors.accent},chipText:{color:colors.textSecondary,fontSize:11,fontFamily:fonts.bodyMedium},chipTextActive:{color:'#fff'},grid:{paddingHorizontal:8,paddingBottom:28},card:{width:'33.333%',paddingHorizontal:4,marginBottom:14},poster:{width:'100%',aspectRatio:2/3,borderRadius:radius.sm,backgroundColor:colors.bgCard},rank:{position:'absolute',left:5,top:5,backgroundColor:'rgba(0,0,0,.8)',paddingHorizontal:5,paddingVertical:3,borderRadius:4},rankText:{color:colors.gold,fontSize:8.5,fontFamily:fonts.bodyBold},score:{position:'absolute',right:5,bottom:5,flexDirection:'row',gap:3,alignItems:'center',backgroundColor:'rgba(0,0,0,.8)',paddingHorizontal:5,paddingVertical:3,borderRadius:4},scoreText:{color:'#fff',fontSize:8.5,fontFamily:fonts.bodySemibold},cardTitle:{color:colors.textPrimary,fontSize:11.5,lineHeight:15,marginTop:5,fontFamily:fonts.bodyMedium},meta:{color:colors.textMuted,fontSize:9.5,marginTop:2,fontFamily:fonts.body},error:{margin:12,padding:10,flexDirection:'row',gap:8,alignItems:'center',backgroundColor:colors.bgCard,borderWidth:1,borderColor:colors.border,borderRadius:radius.md},errorText:{flex:1,color:colors.textSecondary,fontSize:12,fontFamily:fonts.body},empty:{alignItems:'center',paddingTop:70,paddingHorizontal:30},emptyTitle:{color:colors.textPrimary,fontSize:16,fontFamily:fonts.displayMedium,marginTop:12},emptyText:{color:colors.textMuted,fontSize:12,fontFamily:fonts.body,marginTop:5,textAlign:'center'}});
