import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { getTopAnime, DiscoveryCard } from '../api/content';
import { WebAnimeCard, WebSectionHeader } from '../components/WebChrome';
import { colors, fonts, radius } from '../theme';

const filters = [['bypopularity','Most Popular'],['favorite','Most Favorited'],['airing','Top Airing'],['upcoming','Upcoming'],['byrank','By Score']] as const;
export default function TopAnimeScreen() {
  const navigation=useNavigation<any>(); const [filter,setFilter]=useState('bypopularity'); const [items,setItems]=useState<DiscoveryCard[]>([]); const [page,setPage]=useState(1); const [hasNext,setHasNext]=useState(false); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async(f:string,p=1,append=false)=>{setLoading(true);setError(null);try{const r=await getTopAnime(f,p);setItems(v=>append?[...v,...r.data]:r.data);setPage(p);setHasNext(!!r.pagination?.has_next_page)}catch(e:any){setError(e.message??'Failed to load top anime.')}finally{setLoading(false)}},[]);
  useEffect(()=>{load(filter)},[filter,load]); const refresh=async()=>{setRefreshing(true);await load(filter);setRefreshing(false)};
  return <View style={styles.container}><View style={styles.hero}><Text style={styles.kicker}>RANKINGS</Text><Text style={styles.title}>Top Anime</Text><Text style={styles.subtitle}>Discover what everyone is watching</Text><Ionicons name="trophy-outline" size={30} color={colors.gold} style={styles.icon}/></View><FlatList horizontal data={filters} keyExtractor={x=>x[0]} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters} renderItem={({item})=><Pressable onPress={()=>setFilter(item[0])} style={[styles.chip,filter===item[0]&&styles.chipActive]}><Text style={[styles.chipText,filter===item[0]&&styles.chipTextActive]}>{item[1]}</Text></Pressable>}/><WebSectionHeader title="Top Anime" action={filter==='bypopularity'?'Most Popular':undefined}/>{error&&<View style={styles.error}><Ionicons name="cloud-offline-outline" size={17} color={colors.accent}/><Text style={styles.errorText}>{error}</Text></View>}<FlatList data={items} numColumns={3} keyExtractor={x=>String(x.id)} contentContainerStyle={styles.grid} columnWrapperStyle={styles.row} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.accent}/>} onEndReached={()=>{if(!loading&&hasNext)load(filter,page+1,true)}} onEndReachedThreshold={.55} ListEmptyComponent={!loading?<View style={styles.empty}><Ionicons name="trophy-outline" size={40} color={colors.textMuted}/><Text style={styles.emptyTitle}>No rankings available</Text><Text style={styles.emptyText}>Try refreshing in a moment.</Text></View>:null} ListFooterComponent={loading?<ActivityIndicator color={colors.accent} style={{margin:20}}/>:null} renderItem={({item,index})=><View style={styles.card}><View style={styles.rank}><Text style={styles.rankText}>#{item.rank ?? index+1}</Text></View><WebAnimeCard title={item.title} image={item.image} score={item.score} type={item.type} episodes={item.episodes} status={item.userStatus} width={108} onPress={()=>navigation.navigate('AnimeDetail',{id:item.id,title:item.title})}/></View>}/></View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.bgBase},hero:{paddingHorizontal:16,paddingTop:18,paddingBottom:5,position:'relative'},kicker:{color:colors.accent,fontFamily:fonts.displayMedium,fontSize:8,letterSpacing:1.8},title:{color:colors.textPrimary,fontFamily:fonts.display,fontSize:21,marginTop:5},subtitle:{color:colors.textMuted,fontFamily:fonts.body,fontSize:11,marginTop:4},icon:{position:'absolute',right:17,top:22},filters:{paddingHorizontal:14,paddingVertical:9,gap:7,borderBottomWidth:1,borderBottomColor:colors.border},chip:{paddingHorizontal:13,paddingVertical:7,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.bgSurface,marginRight:2},chipActive:{backgroundColor:colors.accent,borderColor:colors.accent},chipText:{color:colors.textSecondary,fontFamily:fonts.bodyMedium,fontSize:10.5},chipTextActive:{color:'#fff'},grid:{paddingHorizontal:12,paddingBottom:30},row:{justifyContent:'flex-start'},card:{width:'33.333%',paddingHorizontal:4,marginBottom:16,position:'relative'},rank:{position:'absolute',zIndex:5,left:8,top:6,backgroundColor:'rgba(0,0,0,.82)',paddingHorizontal:5,paddingVertical:3,borderRadius:4},rankText:{color:colors.gold,fontFamily:fonts.bodyBold,fontSize:8.5},error:{margin:12,padding:10,borderWidth:1,borderColor:colors.borderAccent,borderRadius:8,backgroundColor:colors.bgSurface,flexDirection:'row',gap:8,alignItems:'center'},errorText:{flex:1,color:colors.textSecondary,fontFamily:fonts.body,fontSize:11},empty:{alignItems:'center',paddingTop:65,paddingHorizontal:30},emptyTitle:{color:colors.textPrimary,fontFamily:fonts.displayMedium,fontSize:15,marginTop:12},emptyText:{color:colors.textMuted,fontFamily:fonts.body,fontSize:11,textAlign:'center',marginTop:5}});